name = "LeanMath"
version = "0.1.0"
defaultTargets = ["LeanMath"]

[[lean_lib]]
name = "LeanMath"
globs = [
    "LeanMath.Algebra.+",
    "LeanMath.Data.+",
    "LeanMath.Logic.+",
    "LeanMath.Order.+",
    "LeanMath.Tactic.+",
    "LeanMath.Topology.+",
    "LeanMath.TypeTheory.+",
    # "Math.CategoryTheory.+",
    # "Math.Function.+",
    # "Math.Ops.+",
    # "Math.Relation.+",
    # "Math.Type.+",
    # "Math.Language.+",
    # "Math.Game.+",
    # "Math.AxiomBlame",
]
[leanOptions]
# backward.isDefEq.respectTransparency = false
